Powersjcb/option to disable circles of uncertainty on maps
meshtastic/Meshtastic-Apple pull request #921
Opened 2024-09-08 05:54 UTC by powersjcb

## What changed?

## Why did it change?

## How is this tested?

## Screenshots/Videos (when applicable)

## Checklist

- [ ] My code adheres to the project's coding and style guidelines.
- [ ] I have conducted a self-review of my code.
- [ ] I have commented my code, particularly in complex areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have tested the change to ensure that it works as intended.

2024-09-08 06:00 UTC, powersjcb commented
I'm blocked testing this change at the moment since I don't have the ability to load real node data.

2024-09-08 06:03 UTC, powersjcb commented on Meshtastic/Extensions/UserDefaults.swift
> +	@UserDefault(.meshMapShowLocationPrecision, defaultValue: true)
there's three default values related to this config which is a bit confusing.

2024-09-08 22:36 UTC, powersjcb commented
I finally figured out how to get this compiling for my phone. However, even with the business logic disabled that hides location precision I'm only seeing a circle on the map for my own node.

TBD what's going on here, but I suspect we only ingest position precision when the iphone app sees certain events have happened.

2024-09-11 15:28 UTC, garthvh requested changes
Since most locations are going to be imprecise now I am not a huge fan of this change, if we did implement it, it would need to filter the data in the query and not just hide the circle, we don't use user defaults for the filters.

2024-09-11 16:38 UTC, powersjcb commented
At the moment, this is just an attempt to allow users to "opt-out of clutter" if they don't care about knowing how precise node positions are. 

See this example where entire regions of the map are filled by Location Precision Circles for nodes that have ranges of 5mi and 15mi. When zoomed in the entire map has fill colors driven by the two nodes.

<img width="240" alt="image" src="https://github.com/user-attachments/assets/d81e4f81-b829-4a6d-ab34-5d74209b9832">
<img width="256" alt="image" src="https://github.com/user-attachments/assets/96d5cd51-af33-4e0f-b7f4-00f7d81cdc55">

@garthvh, as a more minimalist change, what would you think about removing or allowing users to toggle fill color for Location Precision Circles?

This wouldn't change the ability to see uncertainty, but it would prevent very large Location Precision Circles from applying fill color to all the nodes they are encapsulating them.

Do you have any sense for how stable we are with this UI? Given the comments on reddit, it feels like it would be helpful to build a tooltip map-legend UI once it's stable.
> Press `(?)` icon on map -> launch modal with map-legend.

2024-09-11 16:51 UTC, powersjcb commented
<img width="238" alt="image" src="https://github.com/user-attachments/assets/fb2bc66d-3da1-433d-be02-e315ac68f6de">

2024-09-13 16:33 UTC, garthvh commented
I really am not seeing a need for this right now, the circles are like 20% and several can stack fine on top of each other. May revisit after 2.5 is the majority firmware.

2024-09-13 16:33 UTC, closed without merging